language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "2.7"

env:
  - DJANGO="django==2.2.9"
  - DJANGO="django==2.1.15"
  - DJANGO="django==2.0.13"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django==2.0.13"
    - python: "2.7"
      env: DJANGO="django==2.1.15"
    - python: "2.7"
      env: DJANGO="django==2.2.9"


install:
  - pip install -r requirements.txt
  - pip install $DJANGO
  - pip install .

before_script:
  - sh .travis-ci/start-sentinel.sh

script:
  - py.test -v

notifications:
  email:
    recipients:
      - aleksey.partilov@lamoda.ru
    on_success: change
    on_failure: change
